// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCf_tDugB0qV36Et5AwIqEYwp4Sm9Nt90',
    appId: '1:627657054894:web:5e91dcfb13e20fd2852b3f',
    messagingSenderId: '627657054894',
    projectId: 'nomad-flutter-final-second',
    authDomain: 'nomad-flutter-final-second.firebaseapp.com',
    storageBucket: 'nomad-flutter-final-second.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1kXP_J6ouBLeTkoIUlpWU86eJWvZnmDQ',
    appId: '1:627657054894:android:cad4fb6873bec428852b3f',
    messagingSenderId: '627657054894',
    projectId: 'nomad-flutter-final-second',
    storageBucket: 'nomad-flutter-final-second.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClmtUuMY5P93oksuwwSK0dXdNN77VrFk8',
    appId: '1:627657054894:ios:3850afd6f4e9c769852b3f',
    messagingSenderId: '627657054894',
    projectId: 'nomad-flutter-final-second',
    storageBucket: 'nomad-flutter-final-second.appspot.com',
    iosBundleId: 'com.example.flutterSemiFinal',
  );
}
